unitDef = {
  unitname               = [[featureunit]],
  name                   = [[Feature attachment]],
  description            = [[Feature attachment]],
  acceleration           = 1,
  blocking               = false,
  brakeRate              = 1,
  buildCostMetal         = 1,
  builder                = false,
  buildPic               = [[levelterra.png]],
  canAttack              = false,
  canMove                = true,
  cantBeTransported      = false,
  capturable             = false,
  category               = [[STUPIDTARGET]],
  collisionVolumeOffsets = [[0 -3000 0]],
  collisionVolumeScales  = [[32 32 32]],
  collisionVolumeType    = [[box]],
  selectionVolumeOffsets = [[0 0 0]],
  selectionVolumeScales  = [[32 16 32]],
  selectionVolumeType    = [[box]],

  customParams           = {
    dontcount      = [[1]],
	cannotcloak    = [[1]],
  },

  footprintX             = 1,
  footprintZ             = 1,

  idleAutoHeal           = 0,
  idleTime               = 1800,
  isFeature              = false,
  kamikaze               = true,
  kamikazeDistance       = 0,
  kamikazeUseLOS         = true,
  levelGround            = false,
  maxDamage              = 1,
  maxSlope               = 255,
  maxVelocity            = 1,
  maxWaterDepth          = 5000,
  minCloakDistance       = 0,
  movementClass          = [[TKBOT1]],
  moveState              = 0,  
  objectName             = [[sphere.s3o]],
  reclaimable            = false,
  script                 = [[nullscript.lua]],
  selfDestructCountdown  = 1,
  sightDistance          = 0,
  stealth                = true,
  turnRate               = 1,
  upright                = false,
  workerTime             = 0,
}

return lowerkeys({ featureunit = unitDef })
